### ISSUE TITLE
Could not resolve "@mapbox/mapbox-gl-draw/src/lib/common_selectors.js"

### ISSUE THREAD

**Issue by fede-qubika** [zakjan/mapbox-gl-draw-waypoint#3]
After installing the package as specified in the documentation, I am getting the following error when running the bundle:

```
[ERROR] Could not resolve "@mapbox/mapbox-gl-draw/src/lib/common_selectors.js"

node_modules/mapbox-gl-draw-waypoint/dist/mapbox-gl-draw-waypoint.esm.js:2:48:
2 │ import { isInactiveFeature, isOfMetaType } from '@mapbox/mapbox-gl-draw/src/lib/common_selectors.js';
```
I see that this import is trying to fetch items from the 'src' folder, which is not included in 'node_modules.' Could it be that I'm making a mistake in some installation step?

**Comment by zakjan** [comment]
Hi, thank you. This is a known incompatibility with `mapbox-gl-draw` 1.4. I've tried to publish a fix in 1.1.2. Could you try if it works?

**Comment by fede-qubika** [comment]
It's working perfectly now. Thank you very much for the quick response!

**Comment by zakjan** [comment]
Perfect, thanks for confirmation, closing. I'll use the same solution in `mapbox-gl-draw-geodesic` as well.
