### ISSUE TITLE
Allow dragging if shift or meta key is pressed

### ISSUE THREAD

**Issue by vcardins** [zakjan/mapbox-gl-draw-waypoint#4]
It would be nice to a add the ability to allow dragging based on event properties so one could check whether the shift or meta key is pressed when dragging. Returning the event as the 2nd argument of the preventFunction would do the job, I guess.

Thanks

**Comment by zakjan** [comment]
Hi, good suggestion. Could you send a PR, please?

**Comment by vcardins** [comment]
Sure, will do that right now!!

**Comment by vcardins** [comment]
PR has been created https://github.com/zakjan/mapbox-gl-draw-waypoint/pull/5

**Comment by zakjan** [comment]
Thanks, released as 1.2.2
